services:
  hacs_installer:
    build:
      context: ./common
      dockerfile: Dockerfile
    container_name: hacs_installer
    restart: unless-stopped
    network_mode: host # 使用宿主机网络模式，绕过 iptables 限制
    volumes:
      - ${HA_CONFIG_PATH:-/usr/share/hassio/homeassistant}:/homeassistant:rw
    environment:
      - HA_CONFIG_PATH=/homeassistant
