services:
  hacs_installer:
    image: ghcr.io/linknlink/hacs_installer:latest
    container_name: hacs_installer
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${HA_CONFIG_PATH:-/usr/share/hassio/homeassistant}:/homeassistant:rw
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HA_CONFIG_PATH=/homeassistant
      - HOST_HA_CONFIG_PATH=${HA_CONFIG_PATH:-/usr/share/hassio/homeassistant}
