services:
  hacs_installer:
    image: ghcr.io/linknlink/hacs_installer:latest
    container_name: hacs_installer
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${HA_CONFIG_PATH:-/usr/share/hassio/homeassistant}:/homeassistant:rw
    environment:
      - HA_CONFIG_PATH=/homeassistant
