services:
  hacs_installer:
    image: ghcr.io/linknlink/hacs_installer:latest
    container_name: hacs_installer
    restart: unless-stopped
    ports:
      - "8202:8202"
    volumes:
      - ${HA_CONFIG_PATH:-/usr/share/hassio/homeassistant}:/homeassistant:rw
    environment:
      - HA_CONFIG_PATH=/homeassistant
